### ISSUE TITLE
Flawless Certus Quartz to Certus Quartz in Slicer Only Gives 1 Gem

### ISSUE THREAD

**Issue by Dyonovan** [trulyno/star-technology#169]
In all other Flawless Gem Slicer recipes it returns 2 of the gems, but for Certus Quartz it only returns 1. The hammer recipe gives the proper amount.

**Comment by trulyno** [comment]
Not an issue on our part, but something with GTCEu:Modern. If the GT devs won't fix this, we will fix it on the modpack side

**Comment by desagas** [comment]
This is still not completed, even thought it is marked as completed. Perhaps you have merged it to an unreleased version of ST?

**Comment by LeDiablePatate** [comment]
It was marked as completed because of :
> Not an issue on our part, but something with GTCEu:Modern.

**Comment by desagas** [comment]
I guess I was reading the line above where @trulyno said "If the GT devs won't fix this, we will fix it on the modpack side."

Since it has been exactly a month since this version of GT was released, with several releases since with both LDLib and GT, and you nor the author of this post have made an issue report with GTCEU:m, I assumed it was never fixed, and that you would have just added the KubeJS code to fix it, as trulyno mentioned. That is why I commented again.

**Comment by UltraPuPower** [comment]
This is a pretty minor bug, as such, no hotfix will be made for it. The next version of StarT will contain a fix. As for the GT side, we are not the persons who discovered it, and it is up to the person who did, or to anyone else experiencing it, to report the bug.
