### ISSUE TITLE
Create: New Age wires dupe

### ISSUE THREAD

**Issue by M4yd3** [trulyno/star-technology#181]
Modpack version: 1.20.1 DELTA HOTFIX 4 - (Beta) - (current)
Minecraft version: 1.20.1
Is on server: No
Modifications done: None
Description: How to reproduce (all blocks are from Create: New Age):
1. Put down two electrical connectors
2. Connect them with any wires
3. Shift-Right click on one of the connectors to grab it with "Carry On"
4. Plop it down somewhere, even on the same spot will do
5. Break the other connector
6. Profit
You can repeat steps 3-4 as many times as you want and get infinite wires. The other connector simply creates new wires without removing the old ones first. I guess you could just blacklist the connectors from "Carry On".

**Comment by UltraPuPower** [comment]
This is a mod issue, not a StarT issue

Also, report number 9 of this bug

**Comment by FubyCutie** [comment]
How is this a mod issue, it is an incompatibility between 2 different mods, it is not the responsibility of either dev to make mods that are compatible, but it _is_ the responsibility of the modpack dev to only use mods that are compatible

**Comment by trulyno** [comment]
The issue is between the mods. Here we accept only issues that are created by the modpack, like recipe conflicts, and not issues of individual mods or interactions between mods.
The issue you reported has been known for while. Since the create wires are insanely cheap, duplicating them makes no sense and provides no advantage.
We _do_ make sure mods are compatible and Create New Age and Carry On are compatible since you can move the connectors and it's a very nice thing. Disabling it just because the wires get duplicated is quite the inconvenience.
If we were talk about whose responsibility is to fix this, it would be the Carry On's developers as their mod is made to be compatible with other mods.
But all of this boils down to one thing: this issue is not ours to fix.

**Comment by FubyCutie** [comment]
Fair enough, I can't blame you for not fixing it, if that's not within the scope of the project, then well, it's not. And I will admit that carry on is an exception, and this bug in general is an exception, and they do take the burden of compatibility here. I just generally don't like the implication that mod incompabilities are caused by the mods themselves, and not the person who put them together.

**Comment by trulyno** [comment]
Modpack developers _integrate_ mods with each other.
Mod developers create _compat_ and/or  _integrations_ with other mods. In fact, some mods exist just from creating compatability between mods, like the [Iris & Oculus Flywheel Compat](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
