### ISSUE TITLE
Large Sieve Cobbleworks 256 items instant and free

### ISSUE THREAD

**Issue by Schrubbls** [trulyno/star-technology#22]
![image](https://github.com/trulyno/star-technology/assets/8899590/ba6991b3-a583-46f4-a47b-61db1ce476a5)

![image](https://github.com/trulyno/star-technology/assets/8899590/de758dc6-bfd8-4ea3-8a1f-fd80c432875d)

![image](https://github.com/trulyno/star-technology/assets/8899590/9cb5ca0d-e05d-4f9d-8990-8c5a74e35065)

![image](https://github.com/trulyno/star-technology/assets/8899590/544c0904-9a0b-4fdc-8438-f6031e39b9fa)

**Comment by trulyno** [comment]
i tested. it works

**Comment by Schrubbls** [comment]
so its intended?

**Comment by trulyno** [comment]
wait

**Comment by trulyno** [comment]
not the free part

**Comment by windyknight** [comment]
Problematic code in the for loop to set the recipes. Loop index acts as the multiplier on the power cost but it starts at 0, causing the first loop's recipes to cost no power. I assume the indices should be (1, 2, 3, 4) instead of the current (0, 1, 2, 3)?

Additionally, would there be a point to using the smaller recipes at all, ignoring the current free state of the 256 recipes? The output size of the largest recipes is 2048. This can be handled by the IV bus, which can be made by the time one can get this multiblock.
