### ISSUE TITLE
All EU powered machinery suddenly stops getting power

### ISSUE THREAD

**Issue by maestroplaya** [trulyno/star-technology#59]
In my attempts to fix my problem with EBF (Electric Blast Furnace) not getting enough EU power, I connected multiple (4) LV 4A Energy Converters in a row and connected all of them with cables (16x Gold Cable) and a wire cutter to the EBF. Suddenly, it's not getting any power. When trying to connect other LV machinery (Lathe, Wiremill, Compressor) it's too doesn't get any EU power, even after switching to 16x Copper Wire

I am attaching the world archive if anyone can get it working (or is it a bug on my end)
[world.zip](https://github.com/user-attachments/files/16043976/world.zip)

**Comment by KgNDK** [comment]
I have looked into this, and the reason for the power converter not working is that you have hooked your power "input" into the "output" of the converter.

To fix this, use a wrench and turn the converter.

Converters, and for that matter transformers, have two sides: input (big) and output (small). To change the way you need power to be converted, you can use a mallet.

You might still have power issues with your EBF. This is due to the EBF needing 120 EU/t, and when subtracting cable loss (which on copper cables is 6 EU per block), you only supply the EBF with around 100 EU/t.

To fix this, use the "super overpowered" super conductors (cable with 0 EU/t cable loss) instead. For LV, this is soul-infused wires.

I hope this helped you.

KgN

**Comment by maestroplaya** [comment]
Yes, this helped me, thanks! I just forgot that i was using a wrong side of the converter

TYSM for other notes too, because it's my first experience with gregtech's LV machines and EU electricity
